# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.twitter.com	TRUE	/	TRUE	1483042297	_mobile_sess	BAh7ByIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNoSGFzaHsABjoKQHVzZWR7ADoQX2NzcmZfdG9rZW4iJTM3Njk4NGQ1NzdlODc0NDlkNWQ5NjM4MjY5YjY2N2E2--88ffe5484ca5b02166c6659e904c8b1e36fdca6c
#HttpOnly_.twitter.com	TRUE	/	TRUE	0	_twitter_sess	BAh7BiIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7AA%253D%253D--1164b91ac812d853b877e93ddb612b7471bebc74
.twitter.com	TRUE	/	TRUE	1509394294	d	32
#HttpOnly_.twitter.com	TRUE	/	TRUE	1540930294	mobile_metrics_token	147785829473284433
#HttpOnly_.twitter.com	TRUE	/	TRUE	1480450294	zrca	5
.twitter.com	TRUE	/	FALSE	1540930294	guest_id	v1%3A147785829457791968
#HttpOnly_.twitter.com	TRUE	/	TRUE	1525119095	kdt	yTBiXvqOEAa0BUApyh0UaRb2Wg7qaWFKMAQSmN4h
.twitter.com	TRUE	/	FALSE	1793218295	remember_checked_on	1
.twitter.com	TRUE	/	TRUE	1793218295	twid	"u=791565175987941377"
mobile.twitter.com	FALSE	/	FALSE	0	lang	en
